# Generated by Django 5.1.2 on 2024-10-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.BigIntegerField(verbose_name='bar code')),
                ('name', models.CharField(max_length=100, verbose_name='name product')),
                ('brand', models.CharField(max_length=100, verbose_name='brand')),
                ('expiration_date', models.DateField(verbose_name='expiration date')),
                ('description', models.TextField(verbose_name='description')),
                ('min_stock', models.IntegerField(verbose_name='min stock')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('provider', models.CharField(max_length=100, verbose_name='provider')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
