# Generated by Django 5.1.2 on 2024-10-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_adjust', models.DateField(auto_now_add=True, verbose_name='adjust')),
                ('type_adjust', models.CharField(max_length=50, verbose_name='type adjust')),
                ('cuantity', models.IntegerField(verbose_name='cuantity')),
                ('reason', models.TextField(verbose_name='reason')),
            ],
            options={
                'verbose_name': 'AdjustInventory',
                'verbose_name_plural': 'AdjustInventorys',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('contact_name', models.CharField(max_length=50, verbose_name='contact name')),
                ('phone', models.BigIntegerField(verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='percents',
            field=models.IntegerField(null=True, verbose_name='percents'),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_date',
            field=models.DateField(null=True, verbose_name='restock date'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
